SELECT 
A.CUSTOMER_ID,
A.FIRST_NAME,
A.LAST_NAME,
A.PHONE_1,
A.EMAIL,
B.AGE,
B.HOME_SIZE,
B.ENERGY_USAGE_PER_MONTH,
B.ENERGY_EFFICIENCY,
B.IS_REGISTERED_FOR_ALERTS,
B.OWNS_HOME,
B.COMPLAINTS,
B.EST_INCOME,
B.CLTV,
B.HAS_THERMOSTAT,
B.HAS_HOME_AUTOMATION,
B.PV_ZONING,
B.WIND_ZONING,
B.SMART_METER_COMMENTS,
B.IS_CAR_OWNER,
B.HAS_EV,
B.HAS_PV,
B.HAS_WIND,
B.TENURE,
B.EBILL,
B.IN_WARRANTY,
B.DEMAND_RESPONSE,
C.CITY,
D.MARITAL_STATUS,
E.GENDER,
F.EDUCATION,
G.EMPLOYMENT,
H.SEGMENT,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_1,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_2,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_3,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_4,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_5,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_6,
I.STD_YRLY_USAGE_CUR_YEAR_MINUS_7,
I.MEDIAN_YRLY_USAGE_CUR_YEAR_MINUS_1
FROM CUSTOMER A
INNER JOIN CST_PROFILES B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
LEFT JOIN LOCATION C
ON B.LOCATION_ID = C.LOCATION_ID
LEFT JOIN MARITAL_STATUS D
ON A.MARITAL_STATUS_ID = D.MARITAL_STATUS_ID
LEFT JOIN GENDER E
ON A.GENDER_ID = E.GENDER_ID
LEFT JOIN EDUCATION F
ON A.EDUCATION_ID = F.EDUCATION_ID
LEFT JOIN EMPLOYMENT G
ON A.EMPLOYMENT_ID = G.EMPLOYMENT_ID
LEFT JOIN CST_SEGMENT H
ON B.CST_SEGMENT_ID = H.CST_SEGMENT_ID
LEFT JOIN STANDARD_YEARLY_USAGE I
ON A.CUSTOMER_ID = I.CUSTOMER_ID;