DROP VIEW WKCREPORT.V_LDM_ENT_ATT_TERMS;

CREATE VIEW WKCREPORT.V_LDM_ENT_ATT_TERMS AS (
SELECT 
cont.CONTAINER_ID CONTAINER_ID, 
cont.NAME CONTAINER_NAME, 
cont.CONTAINER_TYPE CONTAINER_TYPE,
ent.ASSET_ID ENTITY_ID,
ent.NAME ENTITY_NAME, 
ent.ASSET_TYPE ENTITY_TYPE,
ent.RESOURCE_KEY ENTITY_ASSET_RESOURCE_KEY,
--ent.DESCRIPTION ASSET_DESCRIPTION, 
CASE WHEN (NVL(ent_term.ARTIFACT_ID,'') = '') THEN 0 ELSE 1 END ENTITY_MAPPED,
ent_term.ARTIFACT_ID ENTITY_TERM_ARTIFACT_ID,
ent_term.NAME ENTITY_TERM_NAME, 
--ent_term.DESCRIPTION TERM_DESCRIPTION,
ent_cat.CATEGORY_ID ENTITY_CATEGORY_ID,
ent_cat.NAME ENTITY_CATEGORY_NAME, 
--ent_cat.DESCRIPTION CATEGORY_DESCRIPTION,
WKCREPORT.getCatPath(ent_cat.CATEGORY_ID) ENTITY_CATEGORY_PATH,
att.ASSET_ID ATTRIBUTE_ID,
att.NAME ATTRIBUTE_NAME, 
att.ASSET_TYPE ATTRIBUTE_TYPE,
att.RESOURCE_KEY ATTRIBUTE_ASSET_RESOURCE_KEY,
--att.DESCRIPTION ASSET_DESCRIPTION, 
CASE WHEN (NVL(att_term.ARTIFACT_ID,'') = '') THEN 0 ELSE 1 END ATTRIBUTE_MAPPED,
att_term.ARTIFACT_ID ATTRIBUTE_TERM_ARTIFACT_ID,
att_term.NAME ATTRIBUTE_TERM_NAME, 
--att_term.DESCRIPTION TERM_DESCRIPTION,
att_cat.CATEGORY_ID ATTRIBUTE_CATEGORY_ID,
att_cat.NAME ATTRIBUTE_CATEGORY_NAME, 
--att_cat.DESCRIPTION CATEGORY_DESCRIPTION,
WKCREPORT.getCatPath(att_cat.CATEGORY_ID) ATTRIBUTE_CATEGORY_PATH
FROM WKCREPORT.CONTAINERS cont
-- Join to entities in container
INNER JOIN WKCREPORT.CONTAINER_ASSETS ent ON ent.CONTAINER_ID = cont.CONTAINER_ID 
-- Join to get attributes for the entities
INNER JOIN WKCREPORT.CONTAINER_ASSETS_ASSOCIATIONS ent_attr_xr 
     ON ent.ASSET_ID = ent_attr_xr.END1_ASSET_ID AND ent.CONTAINER_ID = ent_attr_xr.END1_CONTAINER_ID AND ent_attr_xr.end1_relationship_type = 'contains'
INNER JOIN WKCREPORT.CONTAINER_ASSETS att 
     ON att.ASSET_ID = ent_attr_xr.END2_ASSET_ID AND att.CONTAINER_ID = ent_attr_xr.END2_CONTAINER_ID AND 
        att.asset_type = 'ibm_logical_model_attribute' AND ent_attr_xr.end2_relationship_type = 'is_contained_in'
-- Join to get terms for the entities
LEFT OUTER JOIN WKCREPORT.GOVERNANCE_ARTIFACT_CONTAINER_ASSOCIATIONS ent_term_xr ON ent_term_xr.ASSET_ID = ent.ASSET_ID and ent_term_xr.CONTAINER_ID = ent.CONTAINER_ID
LEFT OUTER JOIN WKCREPORT.GOVERNANCE_ARTIFACTS ent_term ON ent_term.ARTIFACT_ID = ent_term_xr.ASSOCIATED_ARTIFACT_ID AND ent_term.ARTIFACT_TYPE = 'glossary_term'
LEFT OUTER JOIN WKCREPORT.CATEGORIES ent_cat ON ent_term.PRIMARY_CATEGORY_ID = ent_cat.CATEGORY_ID 
-- Join to get terms for the attributes
LEFT OUTER JOIN WKCREPORT.GOVERNANCE_ARTIFACT_CONTAINER_ASSOCIATIONS att_term_xr ON att_term_xr.ASSET_ID = att.ASSET_ID and att_term_xr.CONTAINER_ID = att.CONTAINER_ID
LEFT OUTER JOIN WKCREPORT.GOVERNANCE_ARTIFACTS att_term ON att_term.ARTIFACT_ID = att_term_xr.ASSOCIATED_ARTIFACT_ID AND att_term.ARTIFACT_TYPE = 'glossary_term'
LEFT OUTER JOIN WKCREPORT.CATEGORIES att_cat ON att_term.PRIMARY_CATEGORY_ID = att_cat.CATEGORY_ID 
WHERE 
ent.asset_type = 'ibm_logical_model_entity'
)
;