SELECT 
A.CUSTOMER_ID,
A.BILLING_DATE,
A.OVERDUE_BALANCE,
A.DUE_DATE,
A.BASE_USAGE,	
A.ALTERNATE_USAGE,	
A.STANDING_CHARGE,	
A.BASE_CHARGE,	
A.ALTERNATE_CHARGE,	
A.LEVY,	
A.TAX,
A.TOTAL_NET,
A.TOTAL_TO_PAY,
F.GENDER,
B.FIRST_NAME,
B.LAST_NAME,
B.PHONE_1,
B.EMAIL,
E.MARITAL_STATUS,
C.AGE, 
C.IS_REGISTERED_FOR_ALERTS,
C.OWNS_HOME,
C.COMPLAINTS,
C.HAS_THERMOSTAT,
C.HAS_HOME_AUTOMATION,
C.PV_ZONING,
C.WIND_ZONING,
C.SMART_METER_COMMENTS,
C.IS_CAR_OWNER,
C.HAS_EV,
C.HAS_PV,
C.HAS_WIND,
C.EBILL,
C.IN_WARRANTY,
D.CITY,
G.EDUCATION,
H.SEGMENT,
I.EMPLOYMENT,
J.CREDIT_HISTORY,
L.BUILDING_TYPE
FROM INVOICE A
LEFT JOIN CUSTOMER B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
LEFT JOIN CST_PROFILES C
ON A.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN LOCATION D
ON C.LOCATION_ID = D.LOCATION_ID
LEFT JOIN MARITAL_STATUS E
ON B.MARITAL_STATUS_ID = E.MARITAL_STATUS_ID
LEFT JOIN GENDER F
ON B.GENDER_ID = F.GENDER_ID
LEFT JOIN EDUCATION G
ON B.EDUCATION_ID = G.EDUCATION_ID
LEFT JOIN CST_SEGMENT H
ON C.CST_SEGMENT_ID = H.CST_SEGMENT_ID 
LEFT JOIN EMPLOYMENT I
ON B.EMPLOYMENT_ID = I.EMPLOYMENT_ID
LEFT JOIN ACCOUNT J
ON A.ACCOUNT_ID = J.ACCOUNT_ID
LEFT JOIN CST_BUILDING_PROFILES K
ON A.CUSTOMER_ID = K.CUSTOMER_ID
LEFT JOIN BUILDING_TYPE L
ON K.BUILDING_TYPE_ID = L.BUILDING_TYPE_ID;
