/*
Sample Materials, provided under license.
Licensed Materials - Property of IBM
© Copyright IBM Corp. 2019. All Rights Reserved.
US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*/

CREATE TABLE SCHEMA_NAME.CUSTOMER_PRODUCT_HISTORY AS
(
	SELECT 
	cs.AGGREGATE_RETAIL_SPEND AS CUSTOMER_SUMMARY_AGGREGATE_RETAIL_SPEND,
	cs.AMOUNT_OF_MANAGEMENT_FEES AS CUSTOMER_SUMMARY_AMOUNT_OF_MANAGEMENT_FEES,
	cs.ANNUAL_INCOME_OTHER AS CUSTOMER_SUMMARY_ANNUAL_INCOME_OTHER,
	cs.ARREARS AS CUSTOMER_SUMMARY_ARREARS,
	cs.AVERAGE_SENTIMENT_SCORE AS CUSTOMER_SUMMARY_AVERAGE_SENTIMENT_SCORE,
	cs.CUSTOMER_ID AS CUSTOMER_SUMMARY_CUSTOMER_ID,
	cs.CUSTOMER_LIFETIME_VALUE AS CUSTOMER_SUMMARY_CUSTOMER_LIFETIME_VALUE,
	cs.END_DATE AS CUSTOMER_SUMMARY_END_DATE,
	cs.EXPERIENCE_NUMBER_OF_PERIODS AS CUSTOMER_SUMMARY_EXPERIENCE_NUMBER_OF_PERIODS,
	cs.EXPERIENCE_RATING AS CUSTOMER_SUMMARY_EXPERIENCE_RATING,
	cs.FINANCIAL_ASSETS AS CUSTOMER_SUMMARY_FINANCIAL_ASSETS,
	cs.FUNDS_UNDER_MANAGEMENT AS CUSTOMER_SUMMARY_FUNDS_UNDER_MANAGEMENT,
	cs.LATEST_SENTIMENT_SCORE AS CUSTOMER_SUMMARY_LATEST_SENTIMENT_SCORE,
	cs.LIABILITIES AS CUSTOMER_SUMMARY_LIABILITIES,
	cs.LIQUID_NET_WORTH AS CUSTOMER_SUMMARY_LIQUID_NET_WORTH,
	cs.NON_FINANCIAL_ASSETS AS CUSTOMER_SUMMARY_NON_FINANCIAL_ASSETS,
	cs.NUMBER_OF_30_DAY_DELINQUENCIES AS CUSTOMER_SUMMARY_NUMBER_OF_30_DAY_DELINQUENCIES,
	cs.NUMBER_OF_ACCOUNTS AS CUSTOMER_SUMMARY_NUMBER_OF_ACCOUNTS,
	cs.NUMBER_OF_ACTIVE_ACCOUNTS AS CUSTOMER_SUMMARY_NUMBER_OF_ACTIVE_ACCOUNTS,
	cs.NUMBER_OF_COMMUNICATIONS AS CUSTOMER_SUMMARY_NUMBER_OF_COMMUNICATIONS,
	cs.NUMBER_OF_COMPLAINTS AS CUSTOMER_SUMMARY_NUMBER_OF_COMPLAINTS,
	cs.NUMBER_OF_CREDIT_BUREAU_INQUIRIES AS CUSTOMER_SUMMARY_NUMBER_OF_CREDIT_BUREAU_INQUIRIES,
	cs.NUMBER_OF_DORMANT_CREDIT_CARD_ARRANGEMENTS AS CUSTOMER_SUMMARY_NUMBER_OF_DORMANT_CREDIT_CARD_ARRANGEMENTS,
	cs.NUMBER_OF_EMAILS AS CUSTOMER_SUMMARY_NUMBER_OF_EMAILS,
	cs.NUMBER_OF_HARD_INQUIRIES AS CUSTOMER_SUMMARY_NUMBER_OF_HARD_INQUIRIES,
	cs.NUMBER_OF_LOGINS AS CUSTOMER_SUMMARY_NUMBER_OF_LOGINS,
	cs.NUMBER_OF_MOBILE_LOGINS AS CUSTOMER_SUMMARY_NUMBER_OF_MOBILE_LOGINS,
	cs.NUMBER_OF_NEW_ACCOUNTS_OPENED AS CUSTOMER_SUMMARY_NUMBER_OF_NEW_ACCOUNTS_OPENED,
	cs.NUMBER_OF_OPEN_COMPLAINTS AS CUSTOMER_SUMMARY_NUMBER_OF_OPEN_COMPLAINTS,
	cs.NUMBER_OF_POSTS AS CUSTOMER_SUMMARY_NUMBER_OF_POSTS,
	cs.NUMBER_OF_RECOMMENDATIONS AS CUSTOMER_SUMMARY_NUMBER_OF_RECOMMENDATIONS,
	cs.NUMBER_OF_REPORTED_CREDIT_CHECKS AS CUSTOMER_SUMMARY_NUMBER_OF_REPORTED_CREDIT_CHECKS,
	cs.NUMBER_OF_REPORTED_MAIL_STOLEN_INCIDENTS AS CUSTOMER_SUMMARY_NUMBER_OF_REPORTED_MAIL_STOLEN_INCIDENTS,
	cs.NUMBER_OF_SOFT_INQUIRIES AS CUSTOMER_SUMMARY_NUMBER_OF_SOFT_INQUIRIES,
	cs.NUMBER_OF_TRADING_PERIODS AS CUSTOMER_SUMMARY_NUMBER_OF_TRADING_PERIODS,
	cs.NUMBER_OF_TRANSACTIONS AS CUSTOMER_SUMMARY_NUMBER_OF_TRANSACTIONS,
	cs.PRIORITY AS CUSTOMER_SUMMARY_PRIORITY,
	cs.REAL_PROPERTY_ASSETS AS CUSTOMER_SUMMARY_REAL_PROPERTY_ASSETS,
	cs.RETURN_10Y AS CUSTOMER_SUMMARY_RETURN_10Y,
	cs.RETURN_1Y AS CUSTOMER_SUMMARY_RETURN_1Y,
	cs.RETURN_2Y AS CUSTOMER_SUMMARY_RETURN_2Y,
	cs.RETURN_3Y AS CUSTOMER_SUMMARY_RETURN_3Y,
	cs.RETURN_5Y AS CUSTOMER_SUMMARY_RETURN_5Y,
	cs.RETURN_LAST_QUARTER AS CUSTOMER_SUMMARY_RETURN_LAST_QUARTER,
	cs.RETURN_SINCE_INCEPTION AS CUSTOMER_SUMMARY_RETURN_SINCE_INCEPTION,
	cs.RETURN_YTD AS CUSTOMER_SUMMARY_RETURN_YTD,
	cs.SOURCE_SYSTEM_ID AS CUSTOMER_SUMMARY_SOURCE_SYSTEM_ID,
	cs.START_DATE AS CUSTOMER_SUMMARY_START_DATE,
	cs.TOP_SPENDING_CATEGORY AS CUSTOMER_SUMMARY_TOP_SPENDING_CATEGORY,
	cs.TOTAL_AMOUNT_OF_BUY_TRADES AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_BUY_TRADES,
	cs.TOTAL_AMOUNT_OF_COMMISSION AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_COMMISSION,
	cs.TOTAL_AMOUNT_OF_DEPOSITS AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_DEPOSITS,
	cs.TOTAL_AMOUNT_OF_INTEREST_EARNED AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_INTEREST_EARNED,
	cs.TOTAL_AMOUNT_OF_INTEREST_FEES AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_INTEREST_FEES,
	cs.TOTAL_AMOUNT_OF_MARKET_CHANGE AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_MARKET_CHANGE,
	cs.TOTAL_AMOUNT_OF_SELL_TRADES AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_SELL_TRADES,
	cs.TOTAL_AMOUNT_OF_TRANSACTION_FEES AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_TRANSACTION_FEES,
	cs.TOTAL_AMOUNT_OF_WAIVED_FEES AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_WAIVED_FEES,
	cs.TOTAL_AMOUNT_OF_WITHDRAWALS AS CUSTOMER_SUMMARY_TOTAL_AMOUNT_OF_WITHDRAWALS,
	cs.TOTAL_CALL_TIME AS CUSTOMER_SUMMARY_TOTAL_CALL_TIME,
	cs.TOTAL_CLOSING_BALANCE AS CUSTOMER_SUMMARY_TOTAL_CLOSING_BALANCE,
	cs.TOTAL_CLOSING_BALANCE_CREDIT_CARDS AS CUSTOMER_SUMMARY_TOTAL_CLOSING_BALANCE_CREDIT_CARDS,
	cs.TOTAL_CLOSING_BALANCE_LOANS AS CUSTOMER_SUMMARY_TOTAL_CLOSING_BALANCE_LOANS,
	cs.TOTAL_CLOSING_CASH_BALANCE AS CUSTOMER_SUMMARY_TOTAL_CLOSING_CASH_BALANCE,
	cs.TOTAL_COMMUNICATIONS_AND_IT_EXPENSE AS CUSTOMER_SUMMARY_TOTAL_COMMUNICATIONS_AND_IT_EXPENSE,
	cs.TOTAL_INWARD_CALLS AS CUSTOMER_SUMMARY_TOTAL_INWARD_CALLS,
	cs.TOTAL_INWARD_COMMUNICATIONS AS CUSTOMER_SUMMARY_TOTAL_INWARD_COMMUNICATIONS,
	cs.TOTAL_INWARD_EMAILS AS CUSTOMER_SUMMARY_TOTAL_INWARD_EMAILS,
	cs.TOTAL_LOGIN_OR_QUERIES AS CUSTOMER_SUMMARY_TOTAL_LOGIN_OR_QUERIES,
	cs.TOTAL_NET_WORTH AS CUSTOMER_SUMMARY_TOTAL_NET_WORTH,
	cs.TOTAL_NUMBER_OF_ACCOUNTS_AS_NON_PRIMARY AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_ACCOUNTS_AS_NON_PRIMARY,
	cs.TOTAL_NUMBER_OF_ACCOUNTS_AS_PRIMARY AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_ACCOUNTS_AS_PRIMARY,
	cs.TOTAL_NUMBER_OF_ACTIVE_COMMUNICATION_THREADS AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_ACTIVE_COMMUNICATION_THREADS,
	cs.TOTAL_NUMBER_OF_ALL_FEES AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_ALL_FEES,
	cs.TOTAL_NUMBER_OF_BUY_TRADES AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_BUY_TRADES,
	cs.TOTAL_NUMBER_OF_DEPOSITS AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_DEPOSITS,
	cs.TOTAL_NUMBER_OF_SELL_TRADES AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_SELL_TRADES,
	cs.TOTAL_NUMBER_OF_UNITS_BOUGHT AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_UNITS_BOUGHT,
	cs.TOTAL_NUMBER_OF_UNITS_SOLD AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_UNITS_SOLD,
	cs.TOTAL_NUMBER_OF_WITHDRAWALS AS CUSTOMER_SUMMARY_TOTAL_NUMBER_OF_WITHDRAWALS,
	cs.TOTAL_OUTWARD_CALLS AS CUSTOMER_SUMMARY_TOTAL_OUTWARD_CALLS,
	cs.TOTAL_OUTWARD_COMMUNICATIONS AS CUSTOMER_SUMMARY_TOTAL_OUTWARD_COMMUNICATIONS,
	cs.TOTAL_OUTWARD_EMAILS AS CUSTOMER_SUMMARY_TOTAL_OUTWARD_EMAILS,
	cs.TRADING_VOLUME AS CUSTOMER_SUMMARY_TRADING_VOLUME,
	cs.TYPE AS CUSTOMER_SUMMARY_TYPE,
	cs.USER_DEFINED_BOOLEAN_1 AS CUSTOMER_SUMMARY_USER_DEFINED_BOOLEAN_1,
	cs.USER_DEFINED_BOOLEAN_2 AS CUSTOMER_SUMMARY_USER_DEFINED_BOOLEAN_2,
	cs.USER_DEFINED_BOOLEAN_3 AS CUSTOMER_SUMMARY_USER_DEFINED_BOOLEAN_3,
	cs.USER_DEFINED_BOOLEAN_4 AS CUSTOMER_SUMMARY_USER_DEFINED_BOOLEAN_4,
	cs.USER_DEFINED_BOOLEAN_5 AS CUSTOMER_SUMMARY_USER_DEFINED_BOOLEAN_5,
	cs.USER_DEFINED_DATE_1 AS CUSTOMER_SUMMARY_USER_DEFINED_DATE_1,
	cs.USER_DEFINED_DATE_2 AS CUSTOMER_SUMMARY_USER_DEFINED_DATE_2,
	cs.USER_DEFINED_DATE_3 AS CUSTOMER_SUMMARY_USER_DEFINED_DATE_3,
	cs.USER_DEFINED_DATE_4 AS CUSTOMER_SUMMARY_USER_DEFINED_DATE_4,
	cs.USER_DEFINED_DATE_5 AS CUSTOMER_SUMMARY_USER_DEFINED_DATE_5,
	cs.USER_DEFINED_INTEGER_1 AS CUSTOMER_SUMMARY_USER_DEFINED_INTEGER_1,
	cs.USER_DEFINED_INTEGER_2 AS CUSTOMER_SUMMARY_USER_DEFINED_INTEGER_2,
	cs.USER_DEFINED_INTEGER_3 AS CUSTOMER_SUMMARY_USER_DEFINED_INTEGER_3,
	cs.USER_DEFINED_INTEGER_4 AS CUSTOMER_SUMMARY_USER_DEFINED_INTEGER_4,
	cs.USER_DEFINED_INTEGER_5 AS CUSTOMER_SUMMARY_USER_DEFINED_INTEGER_5,
	cs.USER_DEFINED_NUMERIC_1 AS CUSTOMER_SUMMARY_USER_DEFINED_NUMERIC_1,
	cs.USER_DEFINED_NUMERIC_2 AS CUSTOMER_SUMMARY_USER_DEFINED_NUMERIC_2,
	cs.USER_DEFINED_NUMERIC_3 AS CUSTOMER_SUMMARY_USER_DEFINED_NUMERIC_3,
	cs.USER_DEFINED_NUMERIC_4 AS CUSTOMER_SUMMARY_USER_DEFINED_NUMERIC_4,
	cs.USER_DEFINED_NUMERIC_5 AS CUSTOMER_SUMMARY_USER_DEFINED_NUMERIC_5,
	cs.USER_DEFINED_STRING_1 AS CUSTOMER_SUMMARY_USER_DEFINED_STRING_1,
	cs.USER_DEFINED_STRING_2 AS CUSTOMER_SUMMARY_USER_DEFINED_STRING_2,
	cs.USER_DEFINED_STRING_3 AS CUSTOMER_SUMMARY_USER_DEFINED_STRING_3,
	cs.USER_DEFINED_STRING_4 AS CUSTOMER_SUMMARY_USER_DEFINED_STRING_4,
	cs.USER_DEFINED_STRING_5 AS CUSTOMER_SUMMARY_USER_DEFINED_STRING_5,
	cust.ACQUISITION_COST AS CUSTOMER_ACQUISITION_COST,
	cust.ADDRESS_HOME_CITY AS CUSTOMER_ADDRESS_HOME_CITY,
	cust.ADDRESS_HOME_COUNTRY AS CUSTOMER_ADDRESS_HOME_COUNTRY,
	cust.ADDRESS_HOME_POSTAL_CODE AS CUSTOMER_ADDRESS_HOME_POSTAL_CODE,
	cust.ADDRESS_HOME_STATE AS CUSTOMER_ADDRESS_HOME_STATE,
	cust.ADDRESS_LAST_CHANGED_DATE AS CUSTOMER_ADDRESS_LAST_CHANGED_DATE,
	cust.ADDRESS_MAILING_CITY AS CUSTOMER_ADDRESS_MAILING_CITY,
	cust.ADDRESS_MAILING_COUNTRY AS CUSTOMER_ADDRESS_MAILING_COUNTRY,
	cust.ADDRESS_MAILING_POSTAL_CODE AS CUSTOMER_ADDRESS_MAILING_POSTAL_CODE,
	cust.ADDRESS_MAILING_STATE AS CUSTOMER_ADDRESS_MAILING_STATE,
	cust.ADDRESS_WORK_CITY AS CUSTOMER_ADDRESS_WORK_CITY,
	cust.ADDRESS_WORK_COUNTRY AS CUSTOMER_ADDRESS_WORK_COUNTRY,
	cust.ADDRESS_WORK_POSTAL_CODE AS CUSTOMER_ADDRESS_WORK_POSTAL_CODE,
	cust.ADDRESS_WORK_STATE AS CUSTOMER_ADDRESS_WORK_STATE,
	cust.ADVERTISING_INDICATOR AS CUSTOMER_ADVERTISING_INDICATOR,
	cust.AGE_RANGE AS CUSTOMER_AGE_RANGE,
	cust.AGGREGATION_OPT_IN_INDICATOR AS CUSTOMER_AGGREGATION_OPT_IN_INDICATOR,
	cust.ANNUAL_INCOME AS CUSTOMER_ANNUAL_INCOME,
	cust.ATTACHMENT_ALLOWED_INDICATOR AS CUSTOMER_ATTACHMENT_ALLOWED_INDICATOR,
	cust.BIRTH_YEAR AS CUSTOMER_BIRTH_YEAR,
	cust.CONTACT_PREFERENCE AS CUSTOMER_CONTACT_PREFERENCE,
	cust.CREDIT_AUTHORITY_LEVEL AS CUSTOMER_CREDIT_AUTHORITY_LEVEL,
	cust.CREDIT_SCORE AS CUSTOMER_CREDIT_SCORE,
	cust.CREDIT_UTILIZATION AS CUSTOMER_CREDIT_UTILIZATION,
	cust.CURRENT_EMPLOYMENT_START_DATE AS CUSTOMER_CURRENT_EMPLOYMENT_START_DATE,
	cust.CUSTOMER_BEHAVIOR AS CUSTOMER_CUSTOMER_BEHAVIOR,
	cust.CUSTOMER_ID AS CUSTOMER_CUSTOMER_ID,
	cust.DATE_FIRST_ACCOUNT_OPENED AS CUSTOMER_DATE_FIRST_ACCOUNT_OPENED,
	cust.DATE_LAST_ACCOUNT_OPENED AS CUSTOMER_DATE_LAST_ACCOUNT_OPENED,
	cust.DEATH_YEAR AS CUSTOMER_DEATH_YEAR,
	cust.DEBT_SERVICE_COVERAGE_RATIO AS CUSTOMER_DEBT_SERVICE_COVERAGE_RATIO,
	cust.EDUCATION_LEVEL AS CUSTOMER_EDUCATION_LEVEL,
	cust.EFFECTIVE_DATE AS CUSTOMER_EFFECTIVE_DATE,
	cust.EMPLOYMENT_STATUS AS CUSTOMER_EMPLOYMENT_STATUS,
	cust.FAMILY_SIZE AS CUSTOMER_FAMILY_SIZE,
	cust.GENDER AS CUSTOMER_GENDER,
	cust.GEOGRAPHIC_AREA_HOME AS CUSTOMER_GEOGRAPHIC_AREA_HOME,
	cust.GEOGRAPHIC_AREA_MAILING AS CUSTOMER_GEOGRAPHIC_AREA_MAILING,
	cust.GEOGRAPHIC_AREA_WORK AS CUSTOMER_GEOGRAPHIC_AREA_WORK,
	cust.HEAD_OF_HOUSEHOLD_INDICATOR AS CUSTOMER_HEAD_OF_HOUSEHOLD_INDICATOR,
	cust.HOME_OWNER_INDICATOR AS CUSTOMER_HOME_OWNER_INDICATOR,
	cust.HOUSEHOLD_ID AS CUSTOMER_HOUSEHOLD_ID,
	cust.IMPORTANCE_LEVEL_CODE AS CUSTOMER_IMPORTANCE_LEVEL_CODE,
	cust.INFLUENCE_SCORE AS CUSTOMER_INFLUENCE_SCORE,
	cust.INTERNET_BANKING_INDICATOR AS CUSTOMER_INTERNET_BANKING_INDICATOR,
	cust.LIFE_CYCLE_STATUS_CHANGE_REASON AS CUSTOMER_LIFE_CYCLE_STATUS_CHANGE_REASON,
	cust.LIFE_CYCLE_STATUS_CODE AS CUSTOMER_LIFE_CYCLE_STATUS_CODE,
	cust.LOYALTY_RATING_CODE AS CUSTOMER_LOYALTY_RATING_CODE,
	cust.MARITAL_STATUS AS CUSTOMER_MARITAL_STATUS,
	cust.MARKET_GROUP AS CUSTOMER_MARKET_GROUP,
	cust.METRIC_BEHAVIOR_PROFILE AS CUSTOMER_METRIC_BEHAVIOR_PROFILE,
	cust.METRIC_BEHAVIOR_PROFILE_2 AS CUSTOMER_METRIC_BEHAVIOR_PROFILE_2,
	cust.METRIC_BEHAVIOR_PROFILE_3 AS CUSTOMER_METRIC_BEHAVIOR_PROFILE_3,
	cust.METRIC_BEHAVIOR_PROFILE_4 AS CUSTOMER_METRIC_BEHAVIOR_PROFILE_4,
	cust.METRIC_BEHAVIOR_PROFILE_5 AS CUSTOMER_METRIC_BEHAVIOR_PROFILE_5,
	cust.METRIC_COMMUNICATION_STYLE AS CUSTOMER_METRIC_COMMUNICATION_STYLE,
	cust.METRIC_FINANCIAL_KNOWLEDGE_RATING AS CUSTOMER_METRIC_FINANCIAL_KNOWLEDGE_RATING,
	cust.METRIC_LATEST_TONE AS CUSTOMER_METRIC_LATEST_TONE,
	cust.METRIC_NET_PROMOTER_SCORE AS CUSTOMER_METRIC_NET_PROMOTER_SCORE,
	cust.METRIC_PERSONALITY_TYPE AS CUSTOMER_METRIC_PERSONALITY_TYPE,
	cust.METRIC_SATISFACTION_LEVEL AS CUSTOMER_METRIC_SATISFACTION_LEVEL,
	cust.METRIC_STRENGTH_OF_RELATIONSHIP AS CUSTOMER_METRIC_STRENGTH_OF_RELATIONSHIP,
	cust.METRIC_TECH_SAVY AS CUSTOMER_METRIC_TECH_SAVY,
	cust.MONTHLY_HOUSING_COST AS CUSTOMER_MONTHLY_HOUSING_COST,
	cust.MONTHLY_NET_INCOME AS CUSTOMER_MONTHLY_NET_INCOME,
	cust.NUMBER_OF_DEPENDENT_ADULTS AS CUSTOMER_NUMBER_OF_DEPENDENT_ADULTS,
	cust.NUMBER_OF_DEPENDENT_CHILDREN AS CUSTOMER_NUMBER_OF_DEPENDENT_CHILDREN,
	cust.OLDEST_DEPENDENT_ADULT_BIRTH_YEAR AS CUSTOMER_OLDEST_DEPENDENT_ADULT_BIRTH_YEAR,
	cust.OLDEST_DEPENDENT_CHILD_BIRTH_YEAR AS CUSTOMER_OLDEST_DEPENDENT_CHILD_BIRTH_YEAR,
	cust.PERSONAL_INTEREST_TOPIC_1 AS CUSTOMER_PERSONAL_INTEREST_TOPIC_1,
	cust.PERSONAL_INTEREST_TOPIC_2 AS CUSTOMER_PERSONAL_INTEREST_TOPIC_2,
	cust.PREFERRED_COMMUNICATION_FORM AS CUSTOMER_PREFERRED_COMMUNICATION_FORM,
	cust.PRIMARY_ADVISOR_ID AS CUSTOMER_PRIMARY_ADVISOR_ID,
	cust.PRIMARY_ADVISOR_ORGANIZATION_ID AS CUSTOMER_PRIMARY_ADVISOR_ORGANIZATION_ID,
	cust.PRIMARY_BRANCH_PROXIMITY AS CUSTOMER_PRIMARY_BRANCH_PROXIMITY,
	cust.PRIMARY_SPOKEN_LANGUAGE AS CUSTOMER_PRIMARY_SPOKEN_LANGUAGE,
	cust.PRIMARY_WRITTEN_LANGUAGE AS CUSTOMER_PRIMARY_WRITTEN_LANGUAGE,
	cust.PROFESSION AS CUSTOMER_PROFESSION,
	cust.PURSUIT AS CUSTOMER_PURSUIT,
	cust.RECORDED_VOICE_SAMPLE_ID AS CUSTOMER_RECORDED_VOICE_SAMPLE_ID,
	cust.REFERRALS_VALUE_CODE AS CUSTOMER_REFERRALS_VALUE_CODE,
	cust.RELATIONSHIP_START_DATE AS CUSTOMER_RELATIONSHIP_START_DATE,
	cust.RETIREMENT_AGE AS CUSTOMER_RETIREMENT_AGE,
	cust.SATISFACTION_RATING_FROM_SURVEY AS CUSTOMER_SATISFACTION_RATING_FROM_SURVEY,
	cust.SECONDARY_ADVISOR_ID AS CUSTOMER_SECONDARY_ADVISOR_ID,
	cust.SECONDARY_ADVISOR_ORGANIZATION_ID AS CUSTOMER_SECONDARY_ADVISOR_ORGANIZATION_ID,
	cust.SPECIAL_TERMS_INDICATOR AS CUSTOMER_SPECIAL_TERMS_INDICATOR,
	cust.STATUS AS CUSTOMER_STATUS,
	cust.STATUS_DATE AS CUSTOMER_STATUS_DATE,
	cust.STATUS_REASON AS CUSTOMER_STATUS_REASON,
	cust.URBAN_CODE AS CUSTOMER_URBAN_CODE,
	cust.USER_DEFINED_BOOLEAN_1 AS CUSTOMER_USER_DEFINED_BOOLEAN_1,
	cust.USER_DEFINED_BOOLEAN_2 AS CUSTOMER_USER_DEFINED_BOOLEAN_2,
	cust.USER_DEFINED_BOOLEAN_3 AS CUSTOMER_USER_DEFINED_BOOLEAN_3,
	cust.USER_DEFINED_BOOLEAN_4 AS CUSTOMER_USER_DEFINED_BOOLEAN_4,
	cust.USER_DEFINED_BOOLEAN_5 AS CUSTOMER_USER_DEFINED_BOOLEAN_5,
	cust.USER_DEFINED_DATE_1 AS CUSTOMER_USER_DEFINED_DATE_1,
	cust.USER_DEFINED_DATE_2 AS CUSTOMER_USER_DEFINED_DATE_2,
	cust.USER_DEFINED_DATE_3 AS CUSTOMER_USER_DEFINED_DATE_3,
	cust.USER_DEFINED_DATE_4 AS CUSTOMER_USER_DEFINED_DATE_4,
	cust.USER_DEFINED_DATE_5 AS CUSTOMER_USER_DEFINED_DATE_5,
	cust.USER_DEFINED_INTEGER_1 AS CUSTOMER_USER_DEFINED_INTEGER_1,
	cust.USER_DEFINED_INTEGER_2 AS CUSTOMER_USER_DEFINED_INTEGER_2,
	cust.USER_DEFINED_INTEGER_3 AS CUSTOMER_USER_DEFINED_INTEGER_3,
	cust.USER_DEFINED_INTEGER_4 AS CUSTOMER_USER_DEFINED_INTEGER_4,
	cust.USER_DEFINED_INTEGER_5 AS CUSTOMER_USER_DEFINED_INTEGER_5,
	cust.USER_DEFINED_NUMERIC_1 AS CUSTOMER_USER_DEFINED_NUMERIC_1,
	cust.USER_DEFINED_NUMERIC_2 AS CUSTOMER_USER_DEFINED_NUMERIC_2,
	cust.USER_DEFINED_NUMERIC_3 AS CUSTOMER_USER_DEFINED_NUMERIC_3,
	cust.USER_DEFINED_NUMERIC_4 AS CUSTOMER_USER_DEFINED_NUMERIC_4,
	cust.USER_DEFINED_NUMERIC_5 AS CUSTOMER_USER_DEFINED_NUMERIC_5,
	cust.USER_DEFINED_STRING_1 AS CUSTOMER_USER_DEFINED_STRING_1,
	cust.USER_DEFINED_STRING_2 AS CUSTOMER_USER_DEFINED_STRING_2,
	cust.USER_DEFINED_STRING_3 AS CUSTOMER_USER_DEFINED_STRING_3,
	cust.USER_DEFINED_STRING_4 AS CUSTOMER_USER_DEFINED_STRING_4,
	cust.USER_DEFINED_STRING_5 AS CUSTOMER_USER_DEFINED_STRING_5,
	cust.WALLET_SHARE_PERCENTAGE AS CUSTOMER_WALLET_SHARE_PERCENTAGE,
	cust.YOUNGEST_DEPENDENT_ADULT_BIRTH_YEAR AS CUSTOMER_YOUNGEST_DEPENDENT_ADULT_BIRTH_YEAR,
	cust.YOUNGEST_DEPENDENT_CHILD_BIRTH_YEAR AS CUSTOMER_YOUNGEST_DEPENDENT_CHILD_BIRTH_YEAR,
	CASE
		WHEN cps_edu.CUSTOMER_ID IS NOT NULL THEN cps_edu.CUSTOMER_ID
		WHEN cps_mp.CUSTOMER_ID IS NOT NULL THEN cps_mp.CUSTOMER_ID
		WHEN cps_brok.CUSTOMER_ID IS NOT NULL THEN cps_brok.CUSTOMER_ID
		WHEN cps_rbrok.CUSTOMER_ID IS NOT NULL THEN cps_rbrok.CUSTOMER_ID
		WHEN cps_fp.CUSTOMER_ID IS NOT NULL THEN cps_fp.CUSTOMER_ID
		WHEN cps_rp.CUSTOMER_ID IS NOT NULL THEN cps_rp.CUSTOMER_ID
		WHEN cps_c.CUSTOMER_ID IS NOT NULL THEN cps_c.CUSTOMER_ID
		WHEN cps_s.CUSTOMER_ID IS NOT NULL THEN cps_s.CUSTOMER_ID
		WHEN cps_ret_bas.CUSTOMER_ID IS NOT NULL THEN cps_ret_bas.CUSTOMER_ID
	END AS CUSTOMER_PRODUCT_SUMMARY_CUSTOMER_ID,
	CASE
		WHEN cps_edu.START_DATE IS NOT NULL THEN cps_edu.START_DATE
		WHEN cps_mp.START_DATE IS NOT NULL THEN cps_mp.START_DATE
		WHEN cps_brok.START_DATE IS NOT NULL THEN cps_brok.START_DATE
		WHEN cps_rbrok.START_DATE IS NOT NULL THEN cps_rbrok.START_DATE
		WHEN cps_fp.START_DATE IS NOT NULL THEN cps_fp.START_DATE
		WHEN cps_rp.START_DATE IS NOT NULL THEN cps_rp.START_DATE
		WHEN cps_c.START_DATE IS NOT NULL THEN cps_c.START_DATE
		WHEN cps_s.START_DATE IS NOT NULL THEN cps_s.START_DATE
		WHEN cps_ret_bas.START_DATE IS NOT NULL THEN cps_ret_bas.START_DATE
	END AS CUSTOMER_PRODUCT_SUMMARY_START_DATE,
	CASE
		WHEN cps_edu.END_DATE IS NOT NULL THEN cps_edu.END_DATE
		WHEN cps_mp.END_DATE IS NOT NULL THEN cps_mp.END_DATE
		WHEN cps_brok.END_DATE IS NOT NULL THEN cps_brok.END_DATE
		WHEN cps_rbrok.END_DATE IS NOT NULL THEN cps_rbrok.END_DATE
		WHEN cps_fp.END_DATE IS NOT NULL THEN cps_fp.END_DATE
		WHEN cps_rp.END_DATE IS NOT NULL THEN cps_rp.END_DATE
		WHEN cps_c.END_DATE IS NOT NULL THEN cps_c.END_DATE
		WHEN cps_s.END_DATE IS NOT NULL THEN cps_s.END_DATE
		WHEN cps_ret_bas.END_DATE IS NOT NULL THEN cps_ret_bas.END_DATE
	END AS CUSTOMER_PRODUCT_SUMMARY_END_DATE,	
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_edu.PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_mp.PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_brok.PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_rbrok.PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_fp.PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_rp.PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_c.PID_CASH_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_s.PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_STATUS,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
	cps_ret_bas.PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_STATUS
	FROM SCHEMA_NAME.CUSTOMER_SUMMARY cs
	INNER JOIN
	(
		-- to join customer table to customer summary table we need to know when the customer
		-- record was effective from and to when
		-- currently have 1 record for effective date for each customer record
		-- the below subquery adds the required dates for each record in customer table
		SELECT 
		A.*,
		B.EFFECTIVE_FROM,
		B.EFFECTIVE_TO
		FROM SCHEMA_NAME.CUSTOMER A
		INNER JOIN
		(
			select 
			c_base.CUSTOMER_ID, 
			c_base.EFFECTIVE_DATE as EFFECTIVE_FROM, 
			min(date(isnull(c_next.EFFECTIVE_DATE, '2100-01-01')) - 1 DAYS) as EFFECTIVE_TO 
			from SCHEMA_NAME.CUSTOMER c_base
			left outer join SCHEMA_NAME.CUSTOMER c_next
			on c_base.CUSTOMER_ID = c_next.CUSTOMER_ID
			and c_base.EFFECTIVE_DATE < c_next.EFFECTIVE_DATE
			group by c_base.CUSTOMER_ID, c_base.EFFECTIVE_DATE
		) B
		ON A.CUSTOMER_ID = B.CUSTOMER_ID
		AND A.EFFECTIVE_DATE = B.EFFECTIVE_FROM
	) cust
	ON cs.CUSTOMER_ID = cust.CUSTOMER_ID
	AND cs.END_DATE >= cust.EFFECTIVE_FROM
	AND cs.END_DATE <= cust.EFFECTIVE_TO
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_EDUCATION_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'Education'
	) cps_edu
	ON cs.CUSTOMER_ID = cps_edu.CUSTOMER_ID AND cs.START_DATE <= cps_edu.START_DATE AND cs.END_DATE >= cps_edu.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_MANAGEDPORTFOLIO_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'ManagedPortfolio'
	) cps_mp
	ON cs.CUSTOMER_ID = cps_mp.CUSTOMER_ID AND cs.START_DATE <= cps_mp.START_DATE AND cs.END_DATE >= cps_mp.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_BROKERAGE_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'Brokerage'
	) cps_brok
	ON cs.CUSTOMER_ID = cps_brok.CUSTOMER_ID AND cs.START_DATE <= cps_brok.START_DATE AND cs.END_DATE >= cps_brok.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_RETIREMENTBROKERAGE_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'RetirementBrokerage'
	) cps_rbrok
	ON cs.CUSTOMER_ID = cps_rbrok.CUSTOMER_ID AND cs.START_DATE <= cps_rbrok.START_DATE AND cs.END_DATE >= cps_rbrok.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_FINANCIALPLAN_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'FinancialPlan'
	) cps_fp
	ON cs.CUSTOMER_ID = cps_fp.CUSTOMER_ID AND cs.START_DATE <= cps_fp.START_DATE AND cs.END_DATE >= cps_fp.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_RETIREMENTPLAN_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'RetirementPlan'
	) cps_rp
	ON cs.CUSTOMER_ID = cps_rp.CUSTOMER_ID AND cs.START_DATE <= cps_rp.START_DATE AND cs.END_DATE >= cps_rp.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_CASH_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'Cash'
	) cps_c
	ON cs.CUSTOMER_ID = cps_c.CUSTOMER_ID AND cs.START_DATE <= cps_c.START_DATE AND cs.END_DATE >= cps_c.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_SAVINGS_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'Savings'
	) cps_s
	ON cs.CUSTOMER_ID = cps_s.CUSTOMER_ID AND cs.START_DATE <= cps_s.START_DATE AND cs.END_DATE >= cps_s.END_DATE
	LEFT JOIN
	(
		SELECT
		DISTINCT
		CUSTOMER_ID,
		START_DATE,
		END_DATE,
		LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLIED_TO_OFFER_INDICATOR,
		LAST_CUSTOMER_REPLY_TIME AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_CUSTOMER_REPLY_TIME,
		LAST_PRODUCT_OFFER_DATE AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_LAST_PRODUCT_OFFER_DATE,
		PRODUCT_OFFERED_INDICATOR AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OFFERED_INDICATOR,
		PRODUCT_OWNED_INDICATOR AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_PRODUCT_OWNED_INDICATOR,
		SENTIMENT_SCORE AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_SENTIMENT_SCORE,
		STATUS AS PID_RETIREMENTBASIC_CUSTOMER_PRODUCT_SUMMARY_STATUS
		FROM SCHEMA_NAME.CUSTOMER_PRODUCT_SUMMARY
		WHERE PRODUCT_ID = 'RetirementBasic'
	) cps_ret_bas
	ON cs.CUSTOMER_ID = cps_ret_bas.CUSTOMER_ID AND cs.START_DATE <= cps_ret_bas.START_DATE AND cs.END_DATE >= cps_ret_bas.END_DATE
) WITH DATA;	