SELECT
A.CUSTOMER_ID,
A.GENDER_ID,
A.FIRST_NAME,
A.LAST_NAME,
A.PHONE_1,
A.EMAIL,
B.AGE,
G.MARITAL_STATUS,
H.EDUCATION,
J.EMPLOYMENT,
B.ENERGY_USAGE_PER_MONTH,
B.ENERGY_EFFICIENCY, 
B.IS_REGISTERED_FOR_ALERTS,
B.OWNS_HOME,
B.COMPLAINTS,
B.CHURN_STATUS,
B.HAS_THERMOSTAT,
B.HAS_HOME_AUTOMATION,
B.PV_ZONING,
B.WIND_ZONING,
B.SMART_METER_COMMENTS,
B.IS_CAR_OWNER,
B.HAS_EV,
B.HAS_PV,
B.HAS_WIND,
B.TENURE,
B.EBILL,
B.IN_WARRANTY,
C.CITY,
D.OFFER AS CURRENT_OFFER,
E.CONTRACT AS CURRENT_CONTRACT,
F.ISSUE AS CURRENT_ISSUE,
I.SEGMENT,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_1,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_2,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_3,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_4,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_5,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_6,
K.STD_YRLY_USAGE_CUR_YEAR_MINUS_7,
K.MEDIAN_YRLY_USAGE_CUR_YEAR_MINUS_1
FROM CUSTOMER A
INNER JOIN CST_PROFILES B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
LEFT JOIN LOCATION C
ON B.LOCATION_ID = C.LOCATION_ID
LEFT JOIN OFFER D
ON B.CURRENT_OFFER_ID = D.OFFER_ID
LEFT JOIN CONTRACT E
ON B.CURRENT_CONTRACT_ID = E.CONTRACT_ID
LEFT JOIN ISSUE F
ON B.ISSUE_ID = F.ISSUE_ID
LEFT JOIN MARITAL_STATUS G
ON A.MARITAL_STATUS_ID = G.MARITAL_STATUS_ID
LEFT JOIN EDUCATION H
ON A.EDUCATION_ID = H.EDUCATION_ID
LEFT JOIN CST_SEGMENT I
ON B.CST_SEGMENT_ID = I.CST_SEGMENT_ID 
LEFT JOIN EMPLOYMENT J
ON A.EMPLOYMENT_ID = J.EMPLOYMENT_ID
LEFT JOIN STANDARD_YEARLY_USAGE K
ON A.CUSTOMER_ID = K.CUSTOMER_ID;
